Repository xh/hoist-react, pull requests merged in 2020-04, with the labels that each got.

#1787 PanelModel supports RefreshMode.
  CHANGELOG.md
  cmp/dock/DockViewModel.js
  cmp/dock/impl/DockViewRefreshContextModel.js
  cmp/tab/TabModel.js
  cmp/tab/impl/TabRefreshContextModel.js
  core/refresh/ManagedRefreshContextModel.js
  core/refresh/index.js
  desktop/cmp/dash/DashViewModel.js
  desktop/cmp/panel/Panel.js
  desktop/cmp/panel/PanelModel.js
  mobile/cmp/navigator/PageModel.js
  mobile/cmp/navigator/impl/NavigatorRefreshContextModel.js
Labels: wip

#1802 Add FormModel.allFields getter
  cmp/form/FormModel.js
Labels: forms

#1818 Fix 'empty flash' due to delayed rendering of framework components.
  cmp/grid/Grid.js
  cmp/grid/GridModel.js
  cmp/grid/impl/ColumnGroupHeader.js
  cmp/grid/impl/ColumnHeader.js
Labels: wip

#1842 Add GridModel.select() convenience method
  cmp/grid/GridModel.js
Labels: grid, small

#1840 Styling fixes to ag-grid popups and column set filter
  cmp/ag-grid/AgGrid.scss
Labels: grid, styles
